# Generated by Django 4.0.4 on 2022-05-28 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(default=5)),
                ('year', models.IntegerField(default=2022)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productlist')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sellerdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
